#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Thu Jul 28 14:32:51 2005

import os,sys,getopt
import wx
from certViewerFrame import certViewerFrame,ParseCertException
import myEncodings


class certViewerApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        self.frame_1 = certViewerFrame(None, -1, "")
        self.SetTopWindow(self.frame_1)
        return 1

    def Show(self):
        self.frame_1.Show()

    def ParseCert(self,filename):
        self.frame_1.setCert(self.frame_1.ParseCert(filename))

# end of class certViewerApp

def printhelp():
    print
    print "Platform independent Certificate Viewer"
    print "\t"+"provided by a.trust (www.a-trust.at)"
    print
    print "start with path to certificate as argument"
    print "start without argument to select a certificate"


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'h',['help'])
        for o, a in opts:
            if o in ('-h','--help'):
                printhelp()
                return
    except (getopt.error, IOError), msg:
        print "Error", msg
        printhelp()
        return

    theApp = certViewerApp(0)
    filename=""
    if len(args)==0:
        strWild="Certificates (*.cer;*.crt;*.pem)|*.cer;*.crt;*.pem|All files (*.*)|*.*"
        dlg=wx.FileDialog(None,"Select a Certificate",wildcard=strWild,style=wx.OPEN|wx.FILE_MUST_EXIST|wx.HIDE_READONLY )
        ret=dlg.ShowModal()
        fname=dlg.GetPath()
        dlg.Destroy()
        if ret == wx.ID_OK:
            filename=fname
        else:
            return
    else:
        filename=args[len(args)-1]

    theApp.Show()
    try:
        ret=theApp.ParseCert(filename)
    except ParseCertException, e:
            message=str(e)
            dlg = wx.MessageDialog(None,message,'Error', wx.OK | wx.ICON_EXCLAMATION)
            dlg.ShowModal()
            dlg.Destroy()
    else:
        theApp.MainLoop()


if __name__ == "__main__":
    main()
