# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Thu Jul 28 14:32:27 2005


####
## TODO:
##   During Export Certificate: possibility to choose PEM|DER,...
##   only one images used by cert & crl Viewer
####

import wx
import imgCertViewer
import os,sys,time
import base64
from utils import Str2Unicode
from pisces import asn1
import myEncodings
import socket
import urllib2


hashOid2Name={"2.5.4.42": 'givenName',
              "2.5.4.3":'commonName',
              "2.5.4.4":'surname',
              "2.5.4.5":'serialNumber',
              "2.5.4.6":'countryName',
              "2.5.4.7":'localityName',
              "2.5.4.8":'stateOrProvinceName',
              "2.5.4.10":'organizationName',
              "2.5.4.11":'organizationalUnitName',
              "2.5.4.12":'title',
              "2.5.4.13":'description',
              "2.5.4.41":'name',
              "2.5.4.42":'givenName',
              "2.5.4.43":'initials',
              "2.5.4.45":'uniqueIdentifier',
              "0.2.262.1.10.7.28":'emailAddress',
              "2.5.29.9":'subjectDirectoryAttributes',
              "2.5.29.14":'subjectKeyIdentifier',
              "2.5.29.15":'keyUsage',
              "2.5.29.17":'subjectAltName',
              "2.5.29.19":'basicConstraints',
              "2.5.29.31":'cRLDistributionPoints',
              "2.5.29.32":'certificatePolicies',
              "2.5.29.35":'authorityKeyIdentifier',
              "2.5.29.37":'Extended Key Usage',
              "1.3.6.1.5.5.7.1.1":'authorityInfoAccess',
              "1.3.6.1.5.5.7.1.3":'qc-Statement',
              "1.2.840.113549.1.9.1":'emailAddress',
              "1.2.40.0.10.1.1.1":"PublicAuthority",
              "1.2.40.0.10.1.1.2":"Dienstleistereigenschaft"}

def OID2Name(sOID):
    if hashOid2Name.has_key(sOID):
        return hashOid2Name[sOID]
    else:
        return sOID

hashOid2ShortName={"2.5.4.42":'GN',
              "2.5.4.3":'CN',
              "2.5.4.4":'SN',
              "2.5.4.6":'C',
              "2.5.4.7":'L',
              "2.5.4.10":'O',
              "2.5.4.11":'OU',
              "2.5.4.12":'T',
              "2.5.4.42":'GN',
              "2.5.4.45":'UI',
              "0.2.262.1.10.7.28":'E',
              "1.2.840.113549.1.9.1":'E'}

class ParseCertException:
    def __init__(self,msg):
        self.msg = msg

    def __str__(self):
        """Convert the exception to a string"""
        return ("Error: %s" %(self.msg))



class certViewerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: certViewerFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.notebook_1 = wx.Notebook(self.panel_2, -1, style=0)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_2_copy = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.sizer_5_staticbox = wx.StaticBox(self.notebook_1_pane_3, -1,"Certificate Chain")
        self.panel_1 = wx.Panel(self.notebook_1_pane_1, -1, style=wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.bmpCert = wx.StaticBitmap(self.panel_1, -1, wx.NullBitmap)
        self.label_1 = wx.StaticText(self.panel_1, -1, "Certificate Information")
        self.static_line_1 = wx.StaticLine(self.panel_1, -1)
        self.lblSubjectCN = wx.StaticText(self.panel_1, -1, "CN")
        self.lblIssuerCN = wx.StaticText(self.panel_1, -1, "CN")
        self.lblValidFrom = wx.StaticText(self.panel_1, -1, "99-99-9999")
        self.lblValidTo = wx.StaticText(self.panel_1, -1, "xx")
        self.static_line_2 = wx.StaticLine(self.panel_1, -1)
        self.label_3 = wx.StaticText(self.panel_1, -1, "Certificate Status verfication not implemented")
        self.static_line_2_copy = wx.StaticLine(self.panel_1, -1)
        self.label_2 = wx.StaticText(self.panel_1, -1, "provided by")
        self.bmpAtrust = wx.StaticBitmap(self.panel_1, -1, wx.NullBitmap)
        self.btnCRL = wx.Button(self.notebook_1_pane_1, -1, "Open &CRL")
        self.btnIssuerStatement = wx.Button(self.notebook_1_pane_1, -1, "Issuer &Statement")
        self.list = wx.ListCtrl(self.notebook_1_pane_2_copy, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.edt = wx.TextCtrl(self.notebook_1_pane_2_copy, -1, "", style=wx.TE_MULTILINE)
        self.btnCopy = wx.Button(self.notebook_1_pane_2_copy, -1, "&Copy to File ...")
        self.treeCtrl = wx.TreeCtrl(self.notebook_1_pane_3, -1, style=wx.SUNKEN_BORDER)
        self.btnViewCertificate = wx.Button(self.notebook_1_pane_3, -1, "&View Certificate")
        self.edtChainStatus = wx.TextCtrl(self.notebook_1_pane_3, -1, "Certificate Status verfication not implemented", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.btnOk = wx.Button(self.panel_2, wx.ID_OK, "&Ok")

        self.__set_properties()
        self.__do_layout()

        wx.EVT_BUTTON(self, self.btnCRL.GetId(), self.OnBtnOpenCRL)
        wx.EVT_LIST_ITEM_SELECTED(self, self.list.GetId(), self.OnListSel)
        wx.EVT_BUTTON(self, self.btnCopy.GetId(), self.btnCopyToFile)
        wx.EVT_TREE_SEL_CHANGED(self, self.treeCtrl.GetId(), self.OnTreeSelChanged)
        wx.EVT_TREE_ITEM_COLLAPSING(self, self.treeCtrl.GetId(), self.OnTreeCollapsing)
        wx.EVT_BUTTON(self, self.btnViewCertificate.GetId(), self.OnBtnViewCert)
        wx.EVT_BUTTON(self, wx.ID_OK, self.OnOk)
        # end wxGlade


    def __set_properties(self):
        # begin wxGlade: certViewerFrame.__set_properties
        self.SetTitle("Certificate")
        self.SetSize((413, 487))
        self.label_1.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_2.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.panel_1.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.btnCRL.Enable(False)
        self.btnIssuerStatement.Enable(False)
        self.notebook_1_pane_1.SetSize((382, 379))
        self.notebook_1_pane_1.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.list.SetSize((372, 120))
        self.edt.SetSize((372, 91))
        self.notebook_1_pane_2_copy.SetSize((382, 379))
        self.notebook_1_pane_2_copy.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.edtChainStatus.SetSize((372, 63))
        self.notebook_1.SetSize((390, 405))
        self.notebook_1.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOW))
        self.btnOk.SetDefault()
        self.panel_2.SetSize((400, 453))
        # end wxGlade
        self.bmpCert = wx.StaticBitmap(self.panel_1, -1, imgCertViewer.getcertBitmap())
        self.bmpAtrust = wx.StaticBitmap(self.panel_1, -1, imgCertViewer.getLogo_SmallBitmap())    

    def __do_layout(self):
        # begin wxGlade: certViewerFrame.__do_layout
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1_ = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.VERTICAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_41 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_6_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_44_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.bmpCert, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_BOTTOM|wx.ADJUST_MINSIZE, 10)
        sizer_3.Add(self.label_1, 0, wx.ALIGN_BOTTOM|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(sizer_3, 0, wx.TOP|wx.EXPAND, 5)
        sizer_2.Add(self.static_line_1, 0, wx.ALL|wx.EXPAND, 5)
        lbl = wx.StaticText(self.panel_1, -1, "Issued to:")
        lbl.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        sizer_4_copy_copy_1.Add(lbl, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 20)
        sizer_4_copy_copy_1.Add(self.lblSubjectCN, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(sizer_4_copy_copy_1, 1, wx.EXPAND, 0)
        lbl2 = wx.StaticText(self.panel_1, -1, "Issued by:")
        lbl2.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        sizer_4_copy_copy_copy.Add(lbl2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 20)
        sizer_4_copy_copy_copy.Add(self.lblIssuerCN, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(sizer_4_copy_copy_copy, 1, wx.EXPAND, 0)
        lbl3 = wx.StaticText(self.panel_1, -1, "Valid From")
        lbl3.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        sizer_44_copy.Add(lbl3, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 20)
        sizer_44_copy.Add(self.lblValidFrom, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL, 5)
        lbl32_copy = wx.StaticText(self.panel_1, -1, "to")
        lbl32_copy.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        sizer_44_copy.Add(lbl32_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_44_copy.Add(self.lblValidTo, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(sizer_44_copy, 1, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_2, 0, wx.ALL|wx.EXPAND, 5)
        sizer_2.Add(self.label_3, 0, wx.LEFT|wx.RIGHT|wx.ADJUST_MINSIZE, 20)
        sizer_2.Add(self.static_line_2_copy, 0, wx.ALL|wx.EXPAND, 5)
        sizer_6_copy.Add(self.label_2, 0, wx.RIGHT|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_6_copy.Add(self.bmpAtrust, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(sizer_6_copy, 1, wx.ALIGN_RIGHT, 0)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(sizer_2)
        sizer_2.Fit(self.panel_1)
        sizer_2.SetSizeHints(self.panel_1)
        sizer_41.Add(self.panel_1, 1, wx.ALL|wx.EXPAND, 10)
        sizer_1.Add(self.btnCRL, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_1.Add(self.btnIssuerStatement, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_41.Add(sizer_1, 0, wx.ALL|wx.ALIGN_RIGHT, 10)
        self.notebook_1_pane_1.SetAutoLayout(True)
        self.notebook_1_pane_1.SetSizer(sizer_41)
        sizer_5_copy.Add(self.list, 1, wx.ALL|wx.EXPAND, 5)
        sizer_5_copy.Add(self.edt, 0, wx.ALL|wx.EXPAND, 5)
        sizer_5_copy.Add(self.btnCopy, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 5)
        self.notebook_1_pane_2_copy.SetAutoLayout(True)
        self.notebook_1_pane_2_copy.SetSizer(sizer_5_copy)
        sizer_5.Add(self.treeCtrl, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        sizer_5.Add(self.btnViewCertificate, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add(sizer_5, 1, wx.ALL|wx.EXPAND, 5)
        label_4 = wx.StaticText(self.notebook_1_pane_3, -1, "Certificate Status:")
        sizer_4.Add(label_4, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        sizer_4.Add(self.edtChainStatus, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND|wx.ADJUST_MINSIZE, 5)
        self.notebook_1_pane_3.SetAutoLayout(True)
        self.notebook_1_pane_3.SetSizer(sizer_4)
        sizer_4.Fit(self.notebook_1_pane_3)
        sizer_4.SetSizeHints(self.notebook_1_pane_3)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "General")
        self.notebook_1.AddPage(self.notebook_1_pane_2_copy, "Details")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Certificate Chain")
        sizer_1_.Add(wx.NotebookSizer(self.notebook_1), 1, wx.ALL|wx.EXPAND, 5)
        sizer_1_.Add(self.btnOk, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 5)
        self.panel_2.SetAutoLayout(True)
        self.panel_2.SetSizer(sizer_1_)
        sizer_7.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_7)
        self.Layout()
        # end wxGlade
        self.hashCert={}
        self.hashList2Key={}
        self.filename=None
        self.app=None
        self.displayHashCert={}
        self.list.InsertColumn(0,"Field",width=150)
        self.list.InsertColumn(1,"Value",width=150)

    def OnListSel(self, event): # wxGlade: certViewerFrame.<event_handler>
        idx=event.m_itemIndex
        sKey=self.list.GetItemText(idx)
        sKey=self.hashList2Key[idx]
        sType=type(self.hashCert[sKey])
        if sType is str:
            s=self.hashCert[sKey]
            if sKey=='serial':
                i=int(s)
                s+=' = '+hex(i)+' hex'
            #s=Str2Unicode(s)
            self.edt.SetValue(Str2Unicode(s))
        elif sType is list:
            s=""
            for i in self.hashCert[sKey]:
                if len(s):
                    s+='\n'
                s+=i
            self.edt.SetValue(Str2Unicode(s))
        elif sType is dict:
            s=""
            for key in self.hashCert[sKey]:
                if len(s):
                    s+='\n'
                #print self.hashCert[sKey][key], " Type: (",type(self.hashCert[sKey][key]),")"
                s+="%s = %s" % (key, self.hashCert[sKey][key]) 
#            s=Str2Unicode(s)
#            self.edt.SetValue(s.encode('utf-8'))
#            print s
#            print Str2Unicode(s)
#            if type(s)==unicode:
#                self.edt.SetValue(s.encode('utf-8'))
#            else:
            self.edt.SetValue(Str2Unicode(s))
        else:
            print "selChange",idx,sKey,sType

    def OnOk(self, event): # wxGlade: certViewerFrame.<event_handler>
        self.Destroy()

    def ParseCert(self,filename):
        self.filename=filename
        try:
            f = open(self.filename, 'rb')
        except IOError, msg:
            print "Error", msg
            raise ParseCertException(str(msg))
            return None
        s=f.read()
        f.close()
        return self.ParseCertFromString(s)

    def ParseCertFromString(self,stream):
        hashCert={}

        # first try to base64-decode
        bBase64=True
        for c in stream:
            if not (c>='A' and c<='Z') and \
               not (c>='a' and c<='z') and \
               not (c>='0' and c<='9') and \
               not c in ['\n','\r','/','-',' ','+','=']:
                bBase64=False
                break
        if bBase64:
            s=str(stream)
            while 1:
                idx=s.find("-----")
                if idx>=0:
                    idxEnd=s.find("-----",idx+4)
                    if idxEnd:
                        s=s.replace(s[idx:idxEnd+5],"")
                    else:
                        break
                else:
                    break
            try:
                s=base64.decodestring(s)
                stream=s
            except:
                pass

        try:
            obj = asn1.parse(stream)
        except ValueError,e:
            raise ParseCertException('ParseError '+str(e))
            return None
        tbsCertificate=obj[0]
        signatureAlgorithm=obj[1]
        oid=str(signatureAlgorithm[0])
        if oid=="1.2.840.113549.1.1.5":
            hashCert['signatureAlgorithm']="sha1withRSAEncryption (1 2 840 113549 1 1 5)"
        elif oid=="1.2.840.113549.1.1.4":
            hashCert['signatureAlgorithm']="md5withRSAEncryption (1 2 840 113549 1 1 4)"
        elif oid=="1.2.840.113549.1.1.3":
            hashCert['signatureAlgorithm']="md4withRSAEncryption (1 2 840 113549 1 1 3)"
        elif oid=="1.2.840.113549.1.1.2":
            hashCert['signatureAlgorithm']="md2withRSAEncryption (1 2 840 113549 1 1 2)"
        elif oid=="1.2.840.113549.1.1.1":
            hashCert['signatureAlgorithm']="rsaEncryption (1 2 840 113549 1 1 1)"
        else:
            hashCert['signatureAlgorithm']=oid

        signatureValue=obj[2]

        #version
        ver=tbsCertificate[0]
        try:
            v=asn1.parse(ver.val)
            hashCert['version']=str(v+1)
        except:
            raise ParseCertException('Not a Certificate (version)')
            return None

        # SerialNumber
        try:
            hashCert['serial']=str(tbsCertificate[1])
        except:
            return -1

        # Issuer
        issuer=tbsCertificate[3]
        hashIssuer={}
        for i in issuer:
            t=self.getOidVal(i)
            hashIssuer[t[0]]=t[1]
        hashCert['issuer']=hashIssuer

        # Subject
        subject=tbsCertificate[5]
        hashSubject={}
        for s in subject:
            t=self.getOidVal(s)
            #print t[1], "  Type=('",type(t[1]),")"
            hashSubject[t[0]]=Str2Unicode(t[1])
            #print t[1], "  Type=('",type(t[1]),")"
        hashCert['subject']=hashSubject
# 
        # Validity
        validity=tbsCertificate[4]
        hashCert['ValidFrom']=self.UTC2LocalTime(validity[0])
        hashCert['ValidTo']=self.UTC2LocalTime(validity[1])


        # Validity
        subjectPublicKeyInfo=tbsCertificate[6]
        oid_algorithm=str(subjectPublicKeyInfo[0][0])
        s=self.bin2hex(subjectPublicKeyInfo[1])
        hashCert['subjectPublicKeyInfo']=[oid_algorithm,s]

        i=7
        try:
            while 1:
                t=tbsCertificate[i]
                if t.tag==3: #extension
                    extension=asn1.parse(t.val)
                    for ex in extension:
                        oid=str(ex[0])
                        if len(ex)==2:
                            bCritical=False
                            extnValue=ex[1]
                        elif len(ex)==3:
                            bCritical=ex[1]
                            extnValue=ex[2]
                        if oid=="2.5.29.9": #subjectDirectoryAttributes
                            l=[]
                            subjectDirectoryAttributes=asn1.parse(extnValue)
                            for sda in subjectDirectoryAttributes:
                                if str(sda[0])=="1.3.6.1.5.5.7.9.1":
                                    s="DateOfBirth"+"="+str(sda[1].val)
                                    l.append(s)
                                elif str(sda[0])=="1.3.6.1.5.5.7.9.2":
                                    s="PlaceOfBirth"+"="+str(sda[1].val)
                                    l.append(s)
                                elif str(sda[0])=="1.3.6.1.5.5.7.9.3":
                                    s="Gender"+"="+str(sda[1].val)
                                    l.append(s)
                                elif str(sda[0])=="1.3.6.1.5.5.7.9.4":
                                    s="countryOfCitizenship"+"="+str(sda[1].val)
                                    l.append(s)
                                elif str(sda[0])=="1.3.6.1.5.5.7.9.5":
                                    s="countryOfResidence"+"="+str(sda[1].val)
                                    l.append(s)
                                else:
                                    l.append(sda[0]+"="+str(sda[1].val))
                            hashCert[oid]=l
                        elif oid=="2.5.29.17":
                            subjectAltName=asn1.parse(extnValue)
                            l=[]
                            for m in subjectAltName:
                                if m.tag==0:
                                    l.append('otherName='+m.val)
                                elif m.tag==1:
                                    l.append('rfc822Name='+m.val)
                                elif m.tag==2:
                                    l.append('dNSName='+m.val)
                                elif m.tag==3:
                                    l.append('x400Address='+m.val)
                                elif m.tag==4:
                                    l.append('directoryName='+m.val)
                                elif m.tag==5:
                                    l.append('ediPartyName='+m.val)
                                elif m.tag==6:
                                    l.append('uniformResourceIdentifier='+m.val)
                                elif m.tag==7:
                                    l.append('iPAddress='+m.val)
                                elif m.tag==8:
                                    l.append('registeredID='+m.val)
                            hashCert[oid]=l
                        elif oid=="2.5.29.31":
                            cRLDPs=asn1.parse(extnValue)
                            for cRLDP in cRLDPs:
                                val=asn1.parse(asn1.parse(cRLDP[0].val).val).val
                                if hashCert.has_key(oid):
                                    hashCert[oid].append(val)
                                else:
                                    hashCert[oid]=[val]
                        elif oid=="2.5.29.32":
                            l=[]
                            l.append(str(asn1.parse(extnValue)[0][0]))
                            try:
                                qualifier=str(asn1.parse(extnValue)[0][1][0][0])
                                if qualifier=="1.3.6.1.5.5.7.2.1":
                                    qualifier='cps'
                                elif qualifier=="1.3.6.1.5.5.7.2.2":
                                    qualifier='unotice'
                                s="%s=%s"%(qualifier,asn1.parse(extnValue)[0][1][0][1])
                                l.append(s)
                            except:
                                pass
                            hashCert[oid]=l
                        elif oid=="1.3.6.1.5.5.7.1.1":
                            hashAIA={}
                            AIAs=asn1.parse(extnValue)
                            for AIA in AIAs:
                                accessMethod=str(AIA[0])
                                url=AIA[1].val
                                if accessMethod=='1.3.6.1.5.5.7.48.2':
                                    try:
                                        p=asn1.parse(url)
                                        url=""
                                        for n in p:
                                            m=n[0]
                                            if len(url):
                                                url+=", "
                                            url+=hashOid2ShortName.get(str(m[0]),str(m[0]))
                                            url+="="
                                            url+=m[1]
                                    except:
                                        pass
                                    if hashAIA.has_key("caIssuers"):
                                        hashAIA["caIssuers"].append(url)
                                    else:
                                        hashAIA["caIssuers"]=[url]
                                elif accessMethod=='1.3.6.1.5.5.7.48.1':
                                    if hashAIA.has_key("ocsp"):
                                        hashAIA["ocsp"].append(url)
                                    else:
                                        hashAIA["ocsp"]=[url]
                            hashCert[oid]=hashAIA
                        elif oid=="2.5.29.35":
                            aki=asn1.parse(extnValue)[0]
                            tag=aki.tag
                            val=aki.val
                            if tag==0:
                                hashCert[oid]=self.bin2hex(val)
                            elif tag==1:
                                print "authorityCertIssuer",val
                            elif tag==2:
                                print "authorityCertSerialNumber",val
                        elif oid=="2.5.29.14":
                            hashCert[oid]=self.bin2hex(extnValue)
                        elif oid=="2.5.29.15":
                            #print "bitstring:",ord(extnValue[0]) # gibt an, dass es ein bitstring ist == 3
                            #print "länge:",ord(extnValue[1]) # gibt die länge in bytes an 
                            unused = ord(extnValue[2]) # gibt die anzhal der unused bits an
                            #print "unused: ",unused
                            bitstring = ord(extnValue[3]) ##  endlich der inhalt
                            #print bitstring
                            bitstring = self.dec2bin(bitstring)[:-unused]
                            
                            listKU = []
                            ku={0:'digitalSignature',
                                1:'nonRepudiation',
                                2:'keyEncipherment',
                                3:'dataEncipherment',
                                4:'keyAgreement',
                                5:'keyCertSign',
                                6:'cRLSign',
                                7:'encipherOnly',
                                8:'decipherOnly'}
            
                            num = 0
                            for ii in bitstring:
                                if ii == "1":
                                    listKU.append(ku[num])
                                num +=1
                            listKU.append(extnValue[3])
                            print listKU
                            self.CertHash[name] = listKU                          
#                            listKU=[]
#                            ku={0:'digitalSignature',
#                                1:'nonRepudiation',
#                                2:'keyEncipherment',
#                                3:'dataEncipherment',
#                                4:'keyAgreement',
#                                5:'keyCertSign',
#                                6:'cRLSign',
#                                7:'encipherOnly',
#                                8:'decipherOnly'}
#                            for k in extnValue:
#                                ii=int(ord(k))
#                                if ku.has_key(ii):
#                                    listKU.append(ku[ii])
#                                else:
#                                    listKU.append(hex(ii))
#                            hashCert[oid]=listKU
                        elif oid=="2.5.29.19":
                            l=[]
                            ext=asn1.parse(extnValue)
                            try:
                                if ext[1]:
                                    l.append('cA=True')
                                else:
                                    l.append('cA=False')
                            except:
                                l.append('cA=False')
                            try:
                                pathLenConstraint=ex[2]
                                l.append('pathLenConstraint=%d' % pathLenConstraint)
                            except:
                                l.append('pathLenConstraint=None')
                            hashCert[oid]=l
                        elif oid=="1.3.6.1.5.5.7.1.3": #qcStatements
                            qcStatements=asn1.parse(extnValue)
                            l=[]
                            for q in qcStatements:
                                try:
                                    l.append(str(q[0]))
                                except:
                                    l.append(str(q))
                            hashCert[oid]=l
                        elif oid=="2.5.29.37": # extKeyUsage
                            ekus=asn1.parse(extnValue)
                            listeku=[]
                            for eku in ekus:
                                seku=str(eku)
                                if seku=="1.3.6.1.5.5.7.3.1":
                                    listeku.append("serverAuth")
                                elif seku=="1.3.6.1.5.5.7.3.2":
                                    listeku.append("clientAuth")
                                elif seku=="1.3.6.1.5.5.7.3.3":
                                    listeku.append("codeSigning")
                                elif seku=="1.3.6.1.5.5.7.3.4":
                                    listeku.append("emailProtection")
                                elif seku=="1.3.6.1.5.5.7.3.5":
                                    listeku.append("ipsecEndSystem")
                                elif seku=="1.3.6.1.5.5.7.3.6":
                                    listeku.append("ipsecTunnel")
                                elif seku=="1.3.6.1.5.5.7.3.7":
                                    listeku.append("ipsecUser")
                                elif seku=="1.3.6.1.5.5.7.3.8":
                                    listeku.append("timeStamping")
                                elif seku=="1.3.6.1.5.5.7.3.9":
                                    listeku.append("ocspSigning")
                                elif seku=="2.16.840.1.113730.4.1":
                                    listeku.append("serverGatedCrypto")
                                else:
                                    listeku.append(seku)
                            hashCert[oid]=listeku
                        elif oid=="1.2.40.0.10.1.1.1": #Behï¿½denkennzeichen
                            p=asn1.parse(extnValue)
                            hashCert[oid]=str(p)
                        elif oid=="1.2.40.0.10.1.1.2": #Dienstleistereigenschaft
                            hashCert[oid]=self.bin2hex(extnValue)
                        else:
                            try:
                                hashCert[oid]=self.bin2hex(extnValue)
                                print "\n\nunknown",oid
                            except:
                                print "Except",sys.exc_info()
                            print "------"
                else:
                    print "unknown ",t.tag
                i+=1
        except:
            if i!=8:
                print "\nException",sys.exc_info()
            #print "Exception-Type:",sys.exc_type()
            pass
        return hashCert

    def setCert(self,hashCertIn):
        self.hashCert=hashCertIn
        self.UpdateGui()
        self.list.SetItemState(0,wx.LIST_STATE_SELECTED|wx.LIST_STATE_FOCUSED,wx.LIST_STATE_SELECTED|wx.LIST_STATE_FOCUSED)

    def dec2bin(self,dec):
        ret = ""
        while dec > 0:
            temp = dec%2
            ret = "%s%s" %(temp,ret)
            dec = dec/2
        return ret
        
    def UpdateGuiHash(self,sKey):
        idx=0
        sVal=Str2Unicode("")
        if self.hashCert.has_key(sKey):
            for key in self.hashCert[sKey]:
                if len(sVal):
                    sVal+=Str2Unicode(", ")
                sFriendlyKey=key
                if key=='commonName':sFriendlyKey='CN'
                elif key=='givenName':sFriendlyKey='GN'
                elif key=='surname':sFriendlyKey='SN'
                elif key=='title':sFriendlyKey='T'
                elif key=='countryName':sFriendlyKey='C'
                elif key=='localityName':sFriendlyKey='L'
                elif key=='organizationName':sFriendlyKey='O'
                elif key=='organizationalUnitName':sFriendlyKey='OU'
                sVal+=Str2Unicode("%s=%s" % (sFriendlyKey,self.hashCert[sKey][key]))
            self.AppendToList(sKey,sVal)
            del self.displayHashCert[sKey]
        else:
            print "Key %s for UpdateGuiHash not found !!!" % sKey

    def UpdateGuiList(self,sKey):
        sVal=""
        if self.hashCert.has_key(sKey):
            for i in self.hashCert[sKey]:
                if len(sVal):
                    sVal+=", "
                sVal+=i
            self.AppendToList(sKey,sVal)
            del self.displayHashCert[sKey]

    def UpdateGuiSingleVal(self,sKey,sName=None):
        if sName==None:
            sName=sKey
        if self.hashCert.has_key(sKey):
            self.AppendToList(sName,self.hashCert[sKey],sKey)
            del self.displayHashCert[sKey]
        else:
            print "Key %s not found !" % sKey

    def getName(self,h):
        s=""
        if h.has_key('commonName'):
            s=h['commonName']
        elif h.has_key('organizationName'):
            s=h['organizationName']
        elif h.has_key('organizationalUnitName'):
            s=h['organizationalUnitName']
        return Str2Unicode(s)

    def UpdateGui(self):
        sSubject=self.getName(self.hashCert['subject'])
        #self.lblSubjectCN.SetLabel(unicode(sSubject,'iso-8859-1').encode('utf-8'))
        self.lblSubjectCN.SetLabel(Str2Unicode(sSubject))

        sIssuer=self.getName(self.hashCert['issuer'])
        #self.lblIssuerCN.SetLabel(unicode(sIssuer,'iso-8859-1').encode('utf-8'))
        self.lblIssuerCN.SetLabel(Str2Unicode(sIssuer))

        self.lblValidFrom.SetLabel(self.hashCert['ValidFrom'][:10])
        self.lblValidTo.SetLabel(self.hashCert['ValidTo'][:10])

        if self.hashCert.has_key("2.5.29.31"):
            self.btnCRL.Enable(True)
        else:
            self.btnCRL.Enable(False)

        ####print self.hashCert
        self.displayHashCert=self.hashCert.copy()
        self.UpdateGuiSingleVal('version')
        self.UpdateGuiSingleVal('serial')
        self.UpdateGuiSingleVal('signatureAlgorithm')
        self.UpdateGuiSingleVal('ValidFrom','ValidFrom')
        self.UpdateGuiSingleVal('ValidTo','ValidTo')
        self.UpdateGuiHash('subject')
        self.UpdateGuiHash('issuer')

        for key in self.displayHashCert.keys():
            ty=type(self.displayHashCert[key])
            if ty==dict:
                self.UpdateGuiHash(key)
            elif ty==list:
                self.UpdateGuiList(key)
            else:
                self.UpdateGuiSingleVal(key)

        self.ProcessCertChain()
####        print self.hashList2Key

    def getCertsDir(self):
        s=os.path.dirname(sys.argv[0])
        s=os.path.join(s,"certs")
        return s

    def getCertChain(self,hashCert):
        sSubject=self.getName(hashCert['subject'])
        sIssuer=self.getName(hashCert['issuer'])
        if sSubject==sIssuer:
            return None
        certDir=self.getCertsDir()
        sFullName=os.path.join(certDir,sIssuer+".crt")
        if os.path.exists(sFullName):
            f=open(sFullName,"rb")
            strCA=f.read()
            f.close()
            h=self.ParseCertFromString(strCA)
            if self.getName(h['subject'])==sIssuer:
                return h
        return self.downloadCert(hashCert)


        
    def downloadCert(self,hashCert):
        if hashCert.has_key("1.3.6.1.5.5.7.1.1"): # AIA
            if hashCert["1.3.6.1.5.5.7.1.1"].has_key("caIssuers"):
                urlCA=self.hashCert["1.3.6.1.5.5.7.1.1"]["caIssuers"]
                if type(urlCA)==list:
                    urlCA=urlCA[0]
                if type(urlCA)!=str:
                    return None
                if urlCA[:4].lower()!='http': ####
                    return None
                TIMEOUT = 1.0
                socket.setdefaulttimeout(TIMEOUT)
                try:
                    #request = urllib2.Request(urlCA)
                    f = urllib2.urlopen(urlCA)
                except:
                    print "Error loading: '%s'"%urlCA
                    return None
                strCA=f.read()
                try:
                    hashCert=self.ParseCertFromString(strCA)
                except:
                    return None
                if hashCert==None:
                    return None
                #print hashCert
                sName=self.getName(hashCert['subject'])
                sName+=".crt"
                certDir=self.getCertsDir()
                if not os.path.exists(certDir):
                    os.mkdir(certDir)
                sFullName=os.path.join(certDir,sName)
                f=open(sFullName,"wb")
                f.write(strCA)
                f.close()
                return hashCert
        return None

    def ProcessCertChain(self):
        h=self.hashCert
        l=[]
        l.append(self.getName(h['subject']))
        while h!=None:
            hNew=self.getCertChain(h)
            if hNew!=None:
                l.append(self.getName(hNew['subject']))
            else: # end of chain
                if self.getName(h['subject'])!=self.getName(h['issuer']):
                    self.edtChainStatus.AppendText("\n! Certificate cannot be verified up to trusted root")
            h=hNew
        l.reverse()
        for n in l:
            if n==l[0]:
                idx=self.treeCtrl.AddRoot(n)
            else:
                idx=self.treeCtrl.AppendItem(idx,n)
            self.treeCtrl.EnsureVisible(idx)

    def getOidVal(self,obj):
        oid=str(obj[0][0])
        if oid=="2.5.4.42": oid='givenName'
        elif oid=="2.5.4.3": oid='commonName'
        elif oid=="2.5.4.4": oid='surname'
        elif oid=="2.5.4.5": oid='serialNumber'
        elif oid=="2.5.4.6": oid='countryName'
        elif oid=="2.5.4.7": oid='localityName'
        elif oid=="2.5.4.8": oid='stateOrProvinceName'
        elif oid=="2.5.4.10": oid='organizationName'
        elif oid=="2.5.4.11": oid='organizationalUnitName'
        elif oid=="2.5.4.12": oid='title'
        elif oid=="2.5.4.13": oid='description'
        elif oid=="2.5.4.41": oid='name'
        elif oid=="2.5.4.42": oid='givenName'
        elif oid=="2.5.4.43": oid='initials'
        elif oid=="2.5.4.45": oid='uniqueIdentifier'
        elif oid=="0.2.262.1.10.7.28": oid='emailAddress'
        elif oid=="1.2.840.113549.1.9.1": oid='emailAddress'


        val=Str2Unicode(obj[0][1])
#        try:
#            val=unicode(obj[0][1],'utf-8')
#        except UnicodeDecodeError:
#            val=unicode(obj[0][1],'iso-8859-1')
#            val=val.replace('\0','')
        return (oid,val)

    def UTC2LocalTime(self,t1):
        t1=t1._parse()
        t1=time.localtime(t1)
        return time.strftime("%Y-%m-%d %H:%M:%S",t1)

    def AppendToList(self,strField,strVal,sKeyIn=None):
        idx=self.list.GetItemCount()
        index=self.list.InsertStringItem(idx,OID2Name(strField))

#        try:
#            strVal=str(strVal)
#        except UnicodeEncodeError:
#            #strVal=strVal.encode('iso-8859-1')
#            #strVal=unicode(strVal,'iso-8859-1').encode('utf-8')
#            strVal=strVal.encode('utf-8')

        self.list.SetStringItem(index,1,strVal) ##### Str2Unicode?
        if sKeyIn!=None:
            sKey=sKeyIn
        else:
            sKey=strField
        self.hashList2Key[index]=sKey

    def bin2hex(self,bin):
        s=""
        i=0
        for c in bin:
            s1=hex(ord(c))[2:]
            if len(s1)==1:
                s1="0"+s1
            s+=s1+" "
            i+=1
            if i==16:
                s+='\n'
                i=0
        return s

    def btnCopyToFile(self, event): # wxGlade: certViewerFrame.<event_handler>
        strWild="Certificates (*.cer;*.crt;*.pem)|*.cer;*.crt;*.pem|All files (*.*)|*.*"
        dlg=wx.FileDialog(self,"Export Certificate",wildcard=strWild,style=wx.HIDE_READONLY|wx.SAVE)
        if dlg.ShowModal() == wx.ID_OK:
            filedest=dlg.GetPath()
            import shutil
            shutil.copy2(self.filename,filedest)
        dlg.Destroy()

    def ViewCert(self):
        idx=self.treeCtrl.GetSelection()
        if idx:
            s=self.treeCtrl.GetItemText(idx)
            certDir=self.getCertsDir()
            sFullName=os.path.join(certDir,s+".crt")
            if sys.platform[:3]=='win':
                sFullName='"'+sFullName+'"'
            os.spawnl(os.P_NOWAIT,sys.executable,sys.executable,sys.argv[0],sFullName)

    def OnBtnViewCert(self, event): # wxGlade: certViewerFrame.<event_handler>
        self.ViewCert()
        event.Skip()

    def OnTreeCollapsing(self, event): # wxGlade: certViewerFrame.<event_handler>
        idx=self.treeCtrl.GetSelection()
        if idx:
            if self.treeCtrl.GetChildrenCount(idx)!=0:
                self.ViewCert()
        event.Veto()

    def OnTreeSelChanged(self, event): # wxGlade: certViewerFrame.<event_handler>
        idx=self.treeCtrl.GetSelection()
        bEnable=False
        if idx:
            if self.treeCtrl.GetChildrenCount(idx)!=0:
                bEnable=True
        self.btnViewCertificate.Enable(bEnable)
        event.Skip()

    def OnBtnOpenCRL(self, event): # wxGlade: certViewerFrame.<event_handler>
        for crldp in self.hashCert["2.5.29.31"]:
            try:
                if sys.platform[:3]=='win':
                    crldp='"'+crldp+'"'
                #print "sys.executable=",sys.executable
                #print "sys.argv[0]=",sys.argv[0]
                
                ## working, but no refresh
                #sCmd='./crlViewer '+crldp+" "+self.hashCert['serial']
                #os.popen(sCmd)
                
                #sCmd=sys.executable.replace('certViewerApp','crlViewerApp')
                ex_cmd=sys.executable

                sCmd='crlViewerApp'
                print 'crldp',crldp
                if sys.argv[0][-3:].lower()=='.py':
                    sCmd+='.py'
                    #print 'ex_cmd',ex_cmd
                    #print 'sCmd',sCmd
                    os.spawnl(os.P_NOWAIT,ex_cmd,ex_cmd,sCmd,crldp,self.hashCert['serial'])
                else:
                    os.spawnl(os.P_NOWAIT,sCmd,sCmd,crldp,self.hashCert['serial'])

            except:
                print "Can't load CRL:",crldp
            else:
                break # success
        event.Skip()

# end of class certViewerFrame


if __name__ == "__main__":
    from certViewerApp import *
    main()
